hidden_size: 32
lr: 0.0002
weight_decay: 0.002
epochs: 200
batch_size: 32
train: false # whether to train the model
tree: false # whether to load the tree dataset or the DAG dataset
splits: [0.8, 0.1, 0.1] # train, val, test split ratios
